### ISSUE TITLE
GET calls fail with swagger client because of empty body in calls

### ISSUE THREAD

**Issue by dhindle** [adobe/aio-lib-customer-profile#29]
### Expected Behaviour
perform a call to experience platform to retrieve a profile

### Actual Behaviour
Getting following error
`error: [CustomerProfileAPISDK:ERROR_ENTITIES] Error TypeError: Request with GET/HEAD method cannot have body
    at new Request (/nodejsAction/irV4eJAV/index.js:176020:10)
    at /nodejsAction/irV4eJAV/index.js:176230:19
    at new Promise (<anonymous>)
    at Object.fetch (/nodejsAction/irV4eJAV/index.js:176228:9)
    at Object.fetch (/nodejsAction/irV4eJAV/index.js:131569:20)
    at _callee$ (/nodejsAction/irV4eJAV/index.js:38978:86)
    at tryCatch (/nodejsAction/irV4eJAV/index.js:183746:40)
    at Generator.invoke [as _invoke] (/nodejsAction/irV4eJAV/index.js:183976:22)
    at Generator.next (/nodejsAction/irV4eJAV/index.js:183801:21)
    at asyncGeneratorStep (/nodejsAction/irV4eJAV/index.js:105437:24)`

#### Steps to Reproduce
Run the below code with proper values for parameters and you get the error

#### Platform and Version
`CLI plugins:
    core:
      @adobe/aio-cli 7.1.0
      @adobe/aio-cli-plugin-app 7.0.2
      @adobe/aio-cli-plugin-auth 2.4.1
      @adobe/aio-cli-plugin-certificate 0.3.0
      @adobe/aio-cli-plugin-config 2.3.0
      @adobe/aio-cli-plugin-console 3.3.0
      @adobe/aio-cli-plugin-events 1.1.5
      @adobe/aio-cli-plugin-info 2.0.0
      @adobe/aio-cli-plugin-runtime 4.0.0
      @oclif/plugin-autocomplete 0.3.0
      @oclif/plugin-help 2.2.3
      @oclif/plugin-not-found 1.2.4
      @oclif/plugin-plugins 1.10.0
      @oclif/plugin-warn-if-update-available 1.7.0`

using version 1.0.4

#### Sample Code that illustrates the problem
`
// initialize sdk
    const client = await CustomerProfile.init(params.tenant, params.orgId, params.apiKey, token)
    // call methods, eg getProfile
    const profile = await client.getProfile({
      entityId: params.entityId,
      entityIdNS: params.entityIdNS
    });
    const response = {
      statusCode: 200,
      body: profile
    }
`
Thanks in advance.

**Comment by dhindle** [comment]
Could be linked to this commit: https://github.com/adobe/aio-lib-campaign-standard/commit/7763af06e0d0886d71085bb9b5270764831abadf

**Comment by meryllblanchet** [comment]
We have a fix for it in #28 - @sandeep-paliwal could you split the PR in two (fix for this issue vs e2e tests)?
